export const menu = [
    {
      id: 1,
      title: "main",
      listItems: [
        {
          id: 1,
          title: "Homepage",
          url: "/",
          icon: "home.svg",
        },
        {
          id: 2,
          title: "Profile",
          url: "/updateDetails",
          icon: "user.svg",
        },
      ],
    },
    {
      id: 2,
      title: "lists",
      listItems: [
        {
          id: 1,
          title: "Students",
          url: "/students",
          icon: "user.svg",
        },
        {
          id: 2,
          title: "Tutor",
          url: "/Tutor",
          icon: "user.svg",
        },
        {
          id: 3,
          title: "HOD",
          url: "/hod",
          icon: "user.svg",
        },
       
      ],
    },
    {
      id: 3,
      title: "general",
      listItems: [
        {
          id: 1,
          title: "Request Letters",
          url: "/requestLetter",
          icon: "note.svg",
        },
       
      ],
    },
    // {
    //   id: 4,
    //   title: "Maintenance",
    //   listItems: [
    //     {
    //       id: 1,
    //       title: "Settings",
    //       url: "/",
    //       icon: "setting.svg",
    //     },
        
    //   ],
    // },
    // {
    //   id: 5,
    //   title: "analytics",
    //   listItems: [
    //     {
    //       id: 1,
    //       title: "Charts",
    //       url: "/",
    //       icon: "chart.svg",
    //     },
    //     {
    //       id: 2,
    //       title: "Logs",
    //       url: "/",
    //       icon: "log.svg",
    //     },
    //   ],
    // },
  ];
  
  export const topDealUsers = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
      username: "Elva McDonald",
      email: "elva@gmail.com",
      amount: "3.668",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Linnie Nelson",
      email: "linnie@gmail.com",
      amount: "3.256",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Brent Reeves",
      email: "brent@gmail.com",
      amount: "2.998",
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Adeline Watson",
      email: "adeline@gmail.com",
      amount: "2.512",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Juan Harrington",
      email: "juan@gmail.com",
      amount: "2.134",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Augusta McGee",
      email: "augusta@gmail.com",
      amount: "1.932",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Angel Thomas",
      email: "angel@gmail.com",
      amount: "1.560",
    },
  ];
  
  export const chartBoxUser = {
    color: "#8884d8",
    icon: "/userIcon.svg",
    title: "Total Users",
    number: "11.238",
    dataKey: "users",
    percentage: 45,
    chartData: [
      { name: "Sun", users: 400 },
      { name: "Mon", users: 600 },
      { name: "Tue", users: 500 },
      { name: "Wed", users: 700 },
      { name: "Thu", users: 400 },
      { name: "Fri", users: 500 },
      { name: "Sat", users: 450 },
    ],
  };
  
  export const chartBoxProduct = {
    color: "skyblue",
    icon: "/productIcon.svg",
    title: "Total Products",
    number: "238",
    dataKey: "products",
    percentage: 21,
    chartData: [
      { name: "Sun", products: 400 },
      { name: "Mon", products: 600 },
      { name: "Tue", products: 500 },
      { name: "Wed", products: 700 },
      { name: "Thu", products: 400 },
      { name: "Fri", products: 500 },
      { name: "Sat", products: 450 },
    ],
  };
  export const chartBoxRevenue = {
    color: "teal",
    icon: "/revenueIcon.svg",
    title: "Total Revenue",
    number: "$56.432",
    dataKey: "revenue",
    percentage: -12,
    chartData: [
      { name: "Sun", revenue: 400 },
      { name: "Mon", revenue: 600 },
      { name: "Tue", revenue: 500 },
      { name: "Wed", revenue: 700 },
      { name: "Thu", revenue: 400 },
      { name: "Fri", revenue: 500 },
      { name: "Sat", revenue: 450 },
    ],
  };
  export const chartBoxConversion = {
    color: "gold",
    icon: "/conversionIcon.svg",
    title: "Total Ratio",
    number: "2.6",
    dataKey: "ratio",
    percentage: 12,
    chartData: [
      { name: "Sun", ratio: 400 },
      { name: "Mon", ratio: 600 },
      { name: "Tue", ratio: 500 },
      { name: "Wed", ratio: 700 },
      { name: "Thu", ratio: 400 },
      { name: "Fri", ratio: 500 },
      { name: "Sat", ratio: 450 },
    ],
  };
  
  export const barChartBoxRevenue = {
    title: "Profit Earned",
    color: "#8884d8",
    dataKey: "profit",
    chartData: [
      {
        name: "Sun",
        profit: 4000,
      },
      {
        name: "Mon",
        profit: 3000,
      },
      {
        name: "Tue",
        profit: 2000,
      },
      {
        name: "Wed",
        profit: 2780,
      },
      {
        name: "Thu",
        profit: 1890,
      },
      {
        name: "Fri",
        profit: 2390,
      },
      {
        name: "Sat",
        profit: 3490,
      },
    ],
  };
  
  export const barChartBoxVisit = {
    title: "Total Visit",
    color: "#FF8042",
    dataKey: "visit",
    chartData: [
      {
        name: "Sun",
        visit: 4000,
      },
      {
        name: "Mon",
        visit: 3000,
      },
      {
        name: "Tue",
        visit: 2000,
      },
      {
        name: "Wed",
        visit: 2780,
      },
      {
        name: "Thu",
        visit: 1890,
      },
      {
        name: "Fri",
        visit: 2390,
      },
      {
        name: "Sat",
        visit: 3490,
      },
    ],
  };
  
  export const userRows = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
      lastName: "Hubbard",
      firstName: "Eula",
      email: "kewez@@gmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
      verified: true,
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Manning",
      firstName: "Stella",
      email: "comhuhmit@gmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
      verified: true,
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Greer",
      firstName: "Mary",
      email: "ujudokon@hottmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
      verified: true,
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Williamson",
      firstName: "Mildred",
      email: "tinhavabe@gmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
      verified: true,
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Gross",
      firstName: "Jose",
      email: "gobtagbes@yahoo.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/769745/pexels-photo-769745.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Sharp",
      firstName: "Jeremy",
      email: "vulca.eder@mail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
      verified: true,
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Lowe",
      firstName: "Christina",
      email: "reso.bilic@gmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/428364/pexels-photo-428364.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Dean",
      firstName: "Garrett",
      email: "codaic@mail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
      verified: true,
    },
    {
      id: 9,
      img: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Parsons",
      firstName: "Leah",
      email: "uzozor@gmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
    },
    {
      id: 10,
      img: "https://images.pexels.com/photos/775358/pexels-photo-775358.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Reid",
      firstName: "Elnora",
      email: "tuhkabapu@gmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
      verified: true,
    },
    {
      id: 11,
      img: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Dunn",
      firstName: "Gertrude",
      email: "gibo@gmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
      verified: true,
    },
    {
      id: 12,
      img: "https://images.pexels.com/photos/774095/pexels-photo-774095.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Williams",
      firstName: "Mark",
      email: "tic.harvey@hotmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
    },
    {
      id: 13,
      img: "https://images.pexels.com/photos/761977/pexels-photo-761977.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Cruz",
      firstName: "Charlotte",
      email: "ceuc@gmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
    },
    {
      id: 14,
      img: "https://images.pexels.com/photos/927022/pexels-photo-927022.jpeg?auto=compress&cs=tinysrgb&w=1600",
      lastName: "Harper",
      firstName: "Sara",
      email: "bafuv@hotmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
    },
    {
      id: 15,
      img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
      lastName: "Griffin",
      firstName: "Eric",
      email: "ubi@gmail.com",
      phone: "123 456 789",
      createdAt: "01.02.2023",
    },
  ];
  
  export const products = [
    {
      id: 1,
      img: "https://store.sony.com.au/on/demandware.static/-/Sites-sony-master-catalog/default/dw1b537bbb/images/PLAYSTATION5W/PLAYSTATION5W.png",
      title: "Playstation 5 Digital Edition",
      color: "white",
      producer: "Sony",
      price: "$250.99",
      createdAt: "01.02.2023",
      inStock: true,
    },
    {
      id: 2,
      img: "https://www.pngmart.com/files/6/Dell-Laptop-PNG-Image.png",
      title: "Dell Laptop KR211822",
      color: "black",
      producer: "Dell",
      price: "$499.99",
      createdAt: "01.02.2023",
      inStock: true,
    },
    {
      id: 3,
      img: "http://images.samsung.com/is/image/samsung/uk-led-tv-hg40ed670ck-hg40ed670ckxxu-001-front",
      title: "Samsung TV 4K SmartTV",
      color: "gray",
      producer: "Samsung",
      price: "$999.49",
      createdAt: "01.02.2023",
      inStock: true,
    },
    {
      id: 4,
      img: "https://raylo.imgix.net/iphone-14-blue.png",
      title: "Apple Iphone 14 Pro Max",
      color: "white",
      producer: "Apple",
      price: "$799.49",
      createdAt: "01.02.2023",
      inStock: true,
    },
    {
      id: 5,
      img: "https://www.signify.com/b-dam/signify/en-aa/about/news/2020/20200903-movie-night-essentials-popcorn-ice-cream-and-the-new-philips-hue-play-gradient-lightstrip/packaging-lighstrip.png",
      title: "Philips Hue Play Gradient",
      color: "rainbow",
      producer: "Philips",
      price: "$39.99",
      createdAt: "01.02.2023",
    },
    {
      id: 6,
      img: "https://www.smartworld.it/wp-content/uploads/2019/09/High_Resolution_PNG-MX-Master-3-LEFT-GRAPHITE.png",
      title: "Logitech MX Master 3",
      color: "black",
      producer: "Logitech",
      price: "$59.49",
      createdAt: "01.02.2023",
      inStock: true,
    },
    {
      id: 7,
      img: "https://www.pngarts.com/files/7/Podcast-Mic-PNG-Picture.png",
      title: "Rode Podcast Microphone",
      color: "gray",
      producer: "Rode",
      price: "$119.49",
      createdAt: "01.02.2023",
    },
    {
      id: 8,
      img: "https://5.imimg.com/data5/SW/VM/MY-5774620/toshiba-split-ac-2-ton-3-star-rated-ras-24s3ks-500x500.png",
      title: "Toshiba Split AC 2",
      color: "white",
      producer: "Toshiba",
      price: "$899.99",
      createdAt: "01.02.2023",
      inStock: true,
    },
    {
      id: 9,
      img: "https://img.productz.com/review_image/102489/preview_sony-kdl-50w800b-50-inch-hdtv-review-superb-picture-102489.png",
      title: "Sony Bravia KDL-47W805A",
      color: "black",
      producer: "Sony",
      price: "$970.49",
      createdAt: "01.02.2023",
    },
    {
      id: 10,
      img: "https://venturebeat.com/wp-content/uploads/2015/07/As_AO1-131_gray_nonglare_win10_03.png?fit=1338%2C1055&strip=all",
      title: "Acer Laptop 16 KL-4804",
      color: "black",
      producer: "Acer",
      price: "$599.99",
      createdAt: "01.02.2023",
      inStock: true,
    },
  ];
  
  
  
  export const singleUser = {
    id: 1,
    title: "John Doe",
    img: "https://images.pexels.com/photos/17397364/pexels-photo-17397364.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    info: {
      username: "Johndoe99",
      fullname: "John Doe",
      email: "johndoe@gmail.com",
      phone: "123 456 789",
      status: "verified",
    },
    chart: {
      dataKeys: [
        { name: "visits", color: "#82ca9d" },
        { name: "clicks", color: "#8884d8" },
      ],
      data: [
        {
          name: "Sun",
          visits: 4000,
          clicks: 2400,
        },
        {
          name: "Mon",
          visits: 3000,
          clicks: 1398,
        },
        {
          name: "Tue",
          visits: 2000,
          clicks: 3800,
        },
        {
          name: "Wed",
          visits: 2780,
          clicks: 3908,
        },
        {
          name: "Thu",
          visits: 1890,
          clicks: 4800,
        },
        {
          name: "Fri",
          visits: 2390,
          clicks: 3800,
        },
        {
          name: "Sat",
          visits: 3490,
          clicks: 4300,
        },
      ],
    },
    activities: [
      {
        text: "John Doe purchased Playstation 5 Digital Edition",
        time: "3 day ago",
      },
      {
        text: "John Doe added 3 items into their wishlist",
        time: "1 week ago",
      },
      {
        text: "John Doe purchased Sony Bravia KD-32w800",
        time: "2 weeks ago",
      },
      {
        text: "John Doe reviewed a product",
        time: "1 month ago",
      },
      {
        text: "John Doe added 1 items into their wishlist",
        time: "1 month ago",
      },
      {
        text: "John Doe reviewed a product",
        time: "2 months ago",
      },
    ],
  };
  export const singleProduct = {
    id: 1,
    title: "Playstation 5 Digital Edition",
    img: "https://store.sony.com.au/on/demandware.static/-/Sites-sony-master-catalog/default/dw1b537bbb/images/PLAYSTATION5W/PLAYSTATION5W.png",
    info: {
      productId: "Ps5SDF1156d",
      color: "white",
      price: "$250.99",
      producer: "Sony",
      export: "Japan",
    },
    chart: {
      dataKeys: [
        { name: "visits", color: "#82ca9d" },
        { name: "orders", color: "#8884d8" },
      ],
      data: [
        {
          name: "Sun",
          visits: 4000,
          orders: 2400,
        },
        {
          name: "Mon",
          visits: 3000,
          orders: 1398,
        },
        {
          name: "Tue",
          visits: 2000,
          orders: 3800,
        },
        {
          name: "Wed",
          visits: 2780,
          orders: 3908,
        },
        {
          name: "Thu",
          visits: 1890,
          orders: 4800,
        },
        {
          name: "Fri",
          visits: 2390,
          orders: 3800,
        },
        {
          name: "Sat",
          visits: 3490,
          orders: 4300,
        },
      ],
    },
    activities: [
      {
        text: "John Doe purchased Playstation 5 Digital Edition",
        time: "3 day ago",
      },
      {
        text: "Jane Doe added Playstation 5 Digital Edition into their wishlist",
        time: "1 week ago",
      },
      {
        text: "Mike Doe purchased Playstation 5 Digital Edition",
        time: "2 weeks ago",
      },
      {
        text: "Anna Doe reviewed the product",
        time: "1 month ago",
      },
      {
        text: "Michael Doe added Playstation 5 Digital Edition into their wishlist",
        time: "1 month ago",
      },
      {
        text: "Helen Doe reviewed the product",
        time: "2 months ago",
      },
    ],
  };

  export const requestLetter = [
    {
      id: 1,
      Name: "John Doe",
      email: "john.doe@example.com",
      designation: "Principal",
      subject: "Request for leave due to family emergency from March 25 to March 30, 2025",
      messageBody: "I kindly request leave from March 25 to March 30 due to a family emergency. I will ensure all pending work is completed before my leave. Please grant me permission to take this leave and let me know if any formalities need to be completed.",
      status: "Pending",
      approvedBy: "HR Department",
    },
    {
      id: 2,
      Name: "Jane Smith",
      email: "jane.smith@example.com",
      designation: "HOD",
      subject: "Permission request to attend an international workshop on latest industry trends",
      messageBody: "I have been invited to attend an international workshop covering the latest industry trends. This event will enhance my skills and benefit our organization. I seek permission to attend and assure that I will submit a report on key takeaways upon my return.",
      status: "Approved",
      approvedBy: "Training Team",
    },
    {
      id: 3,
      Name: "Alex Johnson",
      email: "alex.johnson@example.com",
      designation: "Tutor",
      subject: "Request to upgrade lab equipment for better student practical learning experience",
      messageBody: "The current lab equipment is outdated, making it difficult for students to conduct practical experiments. Upgrading the equipment will greatly improve hands-on learning experiences. Kindly consider approving the budget for new lab tools to enhance the quality of education provided to students.",
      status: "Rejected",
      approvedBy: "Finance Team",
    },
    {
      id: 4,
      Name: "Sophia Lee",
      email: "sophia.lee@example.com",
      designation: "Professor",
      subject: "Application for funding to organize a national-level academic conference in college",
      messageBody: "We plan to organize a national-level academic conference to bring experts together and enhance knowledge sharing. I request funding approval for this event. This initiative will significantly benefit students and faculty members through insightful discussions and research presentations.",
      status: "Pending",
      approvedBy: "Research Committee",
    },
    {
      id: 5,
      Name: "Michael Brown",
      email: "michael.brown@example.com",
      designation: "HOD",
      subject: "Request for approval to implement a mentorship program for new students",
      messageBody: "A mentorship program for new students will help them adjust to the academic environment and improve learning outcomes. I request approval for implementing this initiative, which pairs experienced students with newcomers for guidance and support throughout their academic journey.",
      status: "Approved",
      approvedBy: "Academic Council",
    },
    {
      id: 6,
      Name: "Emma Wilson",
      email: "emma.wilson@example.com",
      designation: "Lecturer",
      subject: "Seeking permission to attend international seminar on artificial intelligence research",
      messageBody: "I have been selected to participate in an international seminar on artificial intelligence research. This seminar will provide valuable insights and networking opportunities. I request permission to attend and assure that I will share my learnings with colleagues after returning.",
      status: "Pending",
      approvedBy: "Vice Chancellor",
    },
    {
      id: 7,
      Name: "Liam Carter",
      email: "liam.carter@example.com",
      designation: "Principal",
      subject: "Request for budget approval to enhance campus security infrastructure measures",
      messageBody: "To ensure the safety of students and staff, we propose upgrading the campus security infrastructure. This includes installing more CCTV cameras and hiring additional security personnel. Kindly approve the necessary budget to implement these improvements at the earliest.",
      status: "Approved",
      approvedBy: "Finance Committee",
    },
    {
      id: 8,
      Name: "Olivia White",
      email: "olivia.white@example.com",
      designation: "Tutor",
      subject: "Application for training program enrollment to improve teaching methodologies",
      messageBody: "I would like to enroll in a professional training program focused on innovative teaching methodologies. This program will help enhance my teaching strategies and benefit students. I kindly request approval to participate in this training and apply my learnings in our institution.",
      status: "Pending",
      approvedBy: "Academic Affairs",
    },
    {
      id: 9,
      Name: "Daniel Harris",
      email: "daniel.harris@example.com",
      designation: "Professor",
      subject: "Proposal to introduce a new interdisciplinary course in university curriculum",
      messageBody: "Introducing a new interdisciplinary course will provide students with broader learning opportunities. This course will combine various fields of study to promote critical thinking and problem-solving skills. I request approval to develop the curriculum and pilot this course next semester.",
      status: "Rejected",
      approvedBy: "Curriculum Committee",
    },
    {
      id: 10,
      Name: "Ava Martinez",
      email: "ava.martinez@example.com",
      designation: "HOD",
      subject: "Request for financial support to organize annual inter-college sports competition",
      messageBody: "Sports play an essential role in student development. We plan to host an inter-college sports competition to encourage participation and team spirit. I request financial support to cover event costs and ensure a successful sports meet for students.",
      status: "Approved",
      approvedBy: "Sports Department",
    },
    {
      id: 11,
      Name: "Lucas Anderson",
      email: "lucas.anderson@example.com",
      designation: "Tutor",
      subject: "Request to conduct additional workshops for students on software development skills",
      messageBody: "To help students gain practical coding experience, I propose conducting extra workshops on software development. These sessions will enhance their programming skills and career readiness. Kindly approve my request to organize these workshops over the next semester.",
      status: "Pending",
      approvedBy: "IT Department",
    },
    {
      id: 12,
      Name: "Emily Walker",
      email: "emily.walker@example.com",
      designation: "Lecturer",
      subject: "Permission request to lead a research study on climate change impact locally",
      messageBody: "I seek permission to conduct a research study on the local impact of climate change. This study aims to provide valuable data to support sustainable development initiatives. I assure that all research activities will align with institutional guidelines and ethical practices.",
      status: "Pending",
      approvedBy: "Research Board",
    },
    {
      id: 13,
      Name: "Ethan Green",
      email: "ethan.green@example.com",
      designation: "Principal",
      subject: "Application for additional funding to enhance library resources and books collection",
      messageBody: "Expanding our library resources is crucial for students and faculty. I request additional funding to acquire more academic books, journals, and digital resources. These enhancements will significantly improve research opportunities and overall learning experiences.",
      status: "Approved",
      approvedBy: "Library Committee",
    },
    // Add more data up to 20 entries...
  ];
  
  export const users = [
    { id: 1, name: "Alex Johnson", email: "alex.johnson123@gmail.com" },
    { id: 2, name: "Emily Smith", email: "emily.smith987@gmail.com" },
    { id: 3, name: "Michael Brown", email: "michael.brown456@gmail.com" },
    { id: 4, name: "Sarah Jones", email: "sarah.jones789@gmail.com" },
    { id: 5, name: "David Wilson", email: "david.wilson234@gmail.com" },
    { id: 6, name: "Olivia Martin", email: "olivia.martin567@gmail.com" },
    { id: 7, name: "James Taylor", email: "james.taylor890@gmail.com" },
    { id: 8, name: "Sophia Anderson", email: "sophia.anderson123@gmail.com" },
    { id: 9, name: "Benjamin Thomas", email: "benjamin.thomas456@gmail.com" },
    { id: 10, name: "Isabella Moore", email: "isabella.moore789@gmail.com" },
    { id: 11, name: "William Jackson", email: "william.jackson234@gmail.com" },
    { id: 12, name: "Ava White", email: "ava.white567@gmail.com" },
    { id: 13, name: "Ethan Harris", email: "ethan.harris890@gmail.com" },
    { id: 14, name: "Mia Clark", email: "mia.clark123@gmail.com" },
    { id: 15, name: "Noah Lewis", email: "noah.lewis456@gmail.com" },
    { id: 16, name: "Charlotte Robinson", email: "charlotte.robinson789@gmail.com" },
    { id: 17, name: "Logan Walker", email: "logan.walker234@gmail.com" },
    { id: 18, name: "Amelia Hall", email: "amelia.hall567@gmail.com" },
    { id: 19, name: "Mason Allen", email: "mason.allen890@gmail.com" },
    { id: 20, name: "Harper Young", email: "harper.young123@gmail.com" }
  ];
  
  
  